### ISSUE TITLE
Unclear group(prop, childProp) functionality

### ISSUE THREAD

**Issue by qoalu** [isaquediasm/sloth.js#3]
Having difficulty understanding
group(prop, childProp)

I see it inverts the object which has a children array, by having the child as main object and the attributes of the parent in the parent property of the original child.

Haven't tried running it but seems docs example is wrong. In the beginning we have 4 children (apartments) and after inverting (grouping) we have only 3.

**Comment by isaquediasm** [comment]
I've just checked it and the example was indeed wrong. It's fixed already. 💯
